jobs:
        include:
                - stage: tests
                  script: echo "`data`" Unit Tests1"&& sleep 5
                  name: "Unit Tests"
                - script: echo "`data` Integration-tests" && sleep 6
                  name: "Integration Tests"
                - stage: deploy
                  name: "Deploy to GCP"
                  script: echo "`data` Deploy to GCP

